# Generated by Django 4.2.1 on 2024-06-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='detalles',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles del Pedido'),
        ),
    ]
