# Generated by Django 4.2.1 on 2024-06-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedidos', '0002_pedido_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='boleta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_pedidos.boleta', verbose_name='Boleta Asociada'),
        ),
    ]
